### ISSUE TITLE
How to add blur like in previews

### ISSUE THREAD

**Issue by jkdduk** [tiredmala/Roundmoled#8]
Add blur to user 'view more' popout
bonus: how to change 'text channel selected' colors?

**Comment by jkdduk** [comment]
![image](https://user-images.githubusercontent.com/98191393/150610008-06600d16-50aa-4e4d-965d-d65a024f466d.png)

**Comment by Rayrsn** [comment]
My version of this theme, [RoundNotmoled](https://github.com/Rayrsn/RoundNotmoled) implements this (plus a couple of fixes to the base theme)
You can add this to your main css file

```css
.backdrop-2ByYRN.withLayer-2VVmpp {
    opacity: 100% !important;
    background: rgba(0,0,0,.6) !important;
    backdrop-filter: blur(5px) !important;
}
```
